version: "3.8"

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - local_pgdata:/path/to/postgres/data

volumes:
  local_pgdata:
